# Generated by Django 4.1.2 on 2022-12-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ENotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=800)),
                ('Name', models.CharField(max_length=400)),
                ('File', models.FileField(upload_to='')),
                ('Disc', models.TextField()),
            ],
        ),
    ]
